extra_student_files:
  - R/arithmetics.R
  - R/matrices.R
  - R/strings.R
  - R/week1.R
  - tests/testthat/testArithmetics.R
  - tests/testthat/testMatrices.R
  - tests/testthat/testStrings.R
  - tests/testthat/testWeek1.R
  - src/correct.R
